### ISSUE TITLE
error on | Loading pipeline components...:  80%  | diffusers has no attribute StableCascadeUNet

### ISSUE THREAD

**Issue by Sgzmust** [Stability-AI/StableCascade#133]
(stable) root@c738c7f8c72f:/home/Python/StableCascade# PYTHONPATH=./ python3 gradio_app/app.py
RUNNING ON: cuda
Loading pipeline components...:   0%|                                                                                                                               | 0/6 [00:00<?, ?it/s]/root/anaconda3/envs/stable/lib/python3.11/site-packages/diffusers/models/lora.py:384: FutureWarning: `LoRACompatibleLinear` is deprecated and will be removed in version 1.0.0. Use of `LoRACompatibleLinear` is deprecated. Please switch to PEFT backend by installing PEFT: `pip install peft`.
  deprecate("LoRACompatibleLinear", "1.0.0", deprecation_message)
Loading pipeline components...: 100%|███████████████████████████████████████| 6/6 [00:01<00:00,  4.39it/s]
Loading pipeline components...:  80%|█████████████████████████████▏                       | 4/5 [00:00<00:00, 38.32it/s]
Traceback (most recent call last):
  File "/home/Python/StableCascade/gradio_app/app.py", line 16, in <module>
    decoder = StableCascadeDecoderPipeline.from_pretrained("/root/.cache/modelscope/hub/AI-ModelScope/stable-cascade", torch_dtype=torch.bfloat16)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/stable/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/stable/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 1263, in from_pretrained
    loaded_sub_model = load_sub_model(
                       ^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/stable/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 443, in load_sub_model
    class_obj, class_candidates = get_class_obj_and_candidates(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/stable/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 347, in get_class_obj_and_candidates
    class_obj = getattr(library, class_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/stable/lib/python3.11/site-packages/diffusers/utils/import_utils.py", line 697, in __getattr__
    raise AttributeError(f"module {self.__name__} has no attribute {name}")
AttributeError: module diffusers has no attribute StableCascadeUNet
——————————————————————————————————————————————————————————
How should I solve this problem?

**Comment by Sgzmust** [comment]
My graphics card is RTx4090
