### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by loboere** [Stability-AI/StableCascade#17]
I'm trying to train a lora  but it gives me an error

!python train_c_lora.py configs/training/finetune_c_3b_lora.yaml

```
Launching Script
Traceback (most recent call last):
  File "/kaggle/working/StableCascade/train_c_lora.py", line 326, in <module>
    device=torch.device(int(os.environ.get("SLURM_LOCALID")))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

**Comment by k8tems** [comment]
`export SLURM_LOCALID=gpu id`
before running the script
in my case:
`export SLURM_LOCALID=0`

**Comment by JJfan0508** [comment]
> I'm trying to train a lora but it gives me an error
> 
> !python train_c_lora.py configs/training/finetune_c_3b_lora.yaml
> 
> ```
> Launching Script
> Traceback (most recent call last):
>   File "/kaggle/working/StableCascade/train_c_lora.py", line 326, in <module>
>     device=torch.device(int(os.environ.get("SLURM_LOCALID")))
> TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
> ```

did you solve this question?

**Comment by rlucatoor** [comment]
See [this comment](https://github.com/Stability-AI/StableCascade/issues/17#issuecomment-1943224405) and [this PR](https://github.com/Stability-AI/StableCascade/pull/35)
