### ISSUE TITLE
Can't train LoRA with single gpu

### ISSUE THREAD

**Issue by k8tems** [Stability-AI/StableCascade#28]
```python
root@neej0vsc8w:/tmp/StableCascade# python3 train/train_c_lora.py configs/training/finetune_c_lora_mbl.yaml
Launching Script
['experiment_id', 'checkpoint_path', 'output_path', 'image_size', 'webdataset_path', 'grad_accum_steps', 'batch_size', 'updates', 'backup_every', 'save_every', 'lr', 'warmup_updates', 'model_version', 'effnet_checkpoint_path', 'previewer_checkpoint_path', 'module_filters', 'rank', 'train_tokens']
Traceback (most recent call last):
  File "/tmp/StableCascade/train/train_c_lora.py", line 330, in <module>
    warpcore()
  File "/tmp/StableCascade/core/__init__.py", line 292, in __call__
    self.setup_ddp(self.config.experiment_id, single_gpu=single_gpu)  # this will change the device to the CUDA rank
  File "/tmp/StableCascade/core/__init__.py", line 146, in setup_ddp
    process_id = int(os.environ.get("SLURM_PROCID"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by k8tems** [comment]
Fixed by modifying the last line in `train/train_c_lora.py`
https://github.com/Stability-AI/StableCascade/blob/00b95475226defb0276e753ee062ddd9d2f33514/train/train_c_lora.py#L330
to:
```python
warpcore(single_gpu=True)
```

I started getting this error after the fix
```python
Traceback (most recent call last):
  File "/tmp/StableCascade/train/train_c_lora.py", line 330, in <module>
    warpcore(single_gpu=True)
  File "/tmp/StableCascade/core/__init__.py", line 360, in __call__
    self.train(data, extras, models, optimizers, schedulers)
  File "/tmp/StableCascade/train/base.py", line 307, in train
    self.save_checkpoints(models, optimizers)
  File "/tmp/StableCascade/train/base.py", line 313, in save_checkpoints
    barrier()
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/distributed_c10d.py", line 3685, in barrier
    opts.device = _get_pg_default_device(group)
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/distributed_c10d.py", line 593, in _get_pg_default_device
    group = group or _get_default_group()
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/distributed_c10d.py", line 940, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
```

I was able to work around this by commenting out `barrier()` in `train/base.py`
https://github.com/Stability-AI/StableCascade/blob/00b95475226defb0276e753ee062ddd9d2f33514/train/base.py#L313
