### ISSUE TITLE
ModuleNotFoundError: No module named 'inference.utils'

### ISSUE THREAD

**Issue by vishwas-agrawal01** [Stability-AI/StableCascade#8]
Try to run the notebook for Image to Image, but can't able to locate the inference.utils
always show:-
                        ModuleNotFoundError: No module named 'inference.utils'

**Comment by mcawte** [comment]
Add the root of the project to your path.

```python
import sys

sys.path.append('./)
``` 

And where it says os.chdir('..'), change that to the root of the project too. For instance, if you have the repo for the project in a folder called Projects on your home drive:

```python
os.chdir('~/Projects/StableCascade')
``` 

You won't be at risk of changing your current working directory further up the tree each time you run the script if you make that change.

**Comment by vishwas-agrawal01** [comment]
after that try to run but still got indentation errors:

with torch.no_grad(), torch.cuda.amp.autocast(dtype=torch.bfloat16):
    # torch.manual_seed(42)

    sampling_c = extras.gdf.sample(
        models.generator, conditions, stage_c_latent_shape,
        unconditions, device=device, **extras.sampling_configs,
    )
    for (sampled_c, _, _) in tqdm(sampling_c, total=extras.sampling_configs['timesteps']):
        sampled_c = sampled_c
        
    # preview_c = models.previewer(sampled_c).float()
    # show_images(preview_c)

    conditions_b['effnet'] = sampled_c
    unconditions_b['effnet'] = torch.zeros_like(sampled_c)

    sampling_b = extras_b.gdf.sample(
        models_b.generator, conditions_b, stage_b_latent_shape,
        unconditions_b, device=device, **extras_b.sampling_configs
    )
    for (sampled_b, _, _) in tqdm(sampling_b, total=extras_b.sampling_configs['timesteps']):
        sampled_b = sampled_b
    sampled = models_b.stage_a.decode(sampled_b).float()

show_images(sampled)



Only working to  sampled_c = sampled_c
after generating the first 20 inference steps, it gives indentation errors:-

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [03:33<00:00, 10.67s/it]>>> 
>>> 
>>> 
>>> 
>>> with torch.no_grad(), torch.cuda.amp.autocast(dtype=torch.bfloat16):
... sampling_b = extras_b.gdf.sample(
  File "<stdin>", line 2
    sampling_b = extras_b.gdf.sample(
    ^^^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 1
>>>         models_b.generator, conditions_b, stage_b_latent_shape,
  File "<stdin>", line 1
    models_b.generator, conditions_b, stage_b_latent_shape,
IndentationError: unexpected indent
>>>         unconditions_b, device=device, **extras_b.sampling_configs
  File "<stdin>", line 1
    unconditions_b, device=device, **extras_b.sampling_configs
IndentationError: unexpected indent
>>>     )
  File "<stdin>", line 1
    )
IndentationError: unexpected indent
>>>     for (sampled_b) in tqdm(sampling_b, total=extras_b.sampling_configs['timesteps']):
  File "<stdin>", line 1
    for (sampled_b) in tqdm(sampling_b, total=extras_b.sampling_configs['timesteps']):
IndentationError: unexpected indent
>>>         sampled_b = sampled_b
  File "<stdin>", line 1
    sampled_b = sampled_b
IndentationError: unexpected indent
>>>     sampled = models_b.stage_a.decode(sampled_b).float()
  File "<stdin>", line 1
    sampled = models_b.stage_a.decode(sampled_b).float()
IndentationError: unexpected indent


Even though I try to correct all indentations, but still not working, maybe I'm missing something, kinda new in this.

**Comment by zelenooki87** [comment]
Also getting this error when try to load code from notebook for super resolution: ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 8
      5 from tqdm import tqdm
      7 os.chdir('..')
----> 8 from inference.utils import *
      9 from core.utils import load_or_fail
     10 from train import ControlNetCore, WurstCoreB

ModuleNotFoundError: No module named 'inference.utils'     please advice! I am using Windows.
